### ISSUE TITLE
Add new device YAML uses deprecated LibreTiny component

### ISSUE THREAD

**Issue by gb0101010101** [libretiny-eu/libretiny#168]
The LibreTiny component was split between supported chip families but the "New Device" button still generates the old format YAML.

EspHome Libretiny v2023.9.0-dev installed within Home Assistant as Addon.

Reproduce: Click on New Device. Select any LibreTiny board. View YAML config. Shows:

```
libretiny:
  board: cb3s
  framework:
    version: dev
```
When it should be:
```
bk72xx:
  board: cb3s
  framework:
    version: dev
```
