### ISSUE TITLE
Problem Compiling a device to work with SmartIR

### ISSUE THREAD

**Issue by jbrandek** [libretiny-eu/libretiny#187]
working with a bk72xx board cbu

I have a problem when i try to compile a device to work with smartir
i need to add a service api:
```
api:
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
````
but when i do i get this error:
````
|-- Image 1: raw_firmware.elf
/data/cache/platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: .pioenvs/ir-gel/src/main.cpp.o: in function `esphome::api::UserServiceBase<std::vector<long, std::allocator<long> > >::encode_list_service_response()':
/data/build/ir-gel/src/esphome/components/api/user_services.h:35: undefined reference to `esphome::api::enums::ServiceArgType esphome::api::to_service_arg_type<std::vector<long, std::allocator<long> > >()'
collect2: error: ld returned 1 exit status
|-- Generated file not found: .pioenvs/ir-gel/raw_firmware.elf
*** [.pioenvs/ir-gel/raw_firmware.elf] Error 1
========================= [FAILED] Took 102.21 seconds =========================
````

tried same code with a esp8266 and everything compiles perfect
