### ISSUE TITLE
Generic RGBWW Ceiling Light Issues

### ISSUE THREAD

**Issue by banter7702** [libretiny-eu/libretiny#192]
Hi, its me with some remote issues again.

I flashed a generic rgbww ceiling light, identical with this one:
[[DUMP] [CB3S] [BK7231N] Eacam 24W RGBCW Ceiling ](https://github.com/tuya-cloudcutter/tuya-cloudcutter/issues/361)

So, I had this same initial problem in that topic where pins cant be found or extracted, I used esphome kickstarter and ltchiptool to extract it but same problem.

So I manually search it and found all the rgb cw ww pwms.

But it has problems. The rgb is not optimal. Sometimes it will turn off if I fully go to 2700k or 6500k, I had to go to red to make color temp work properly. Same goes to fully going down to lowest brightness, it turns off.

And my biggest gripe is that, I lost the remote functionality. We'll, if it would be me, its fine, but the people in the house needs it. How do I restore it? And some of its fancy features such as scenes?

Here is my esphome config:

```
esphome:
  name: ceiling-lamp
  friendly_name: Ceiling Lamp

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

preferences:
  flash_write_interval: 10s

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Ceiling-Lamp Fallback Hotspot"
    password: "redacted"

output:
  - platform: ledc
    id: output_red
    pin: P8
  - platform: ledc
    id: output_green
    pin: P24
  - platform: ledc
    id: output_blue
    pin: P26
  - platform: ledc
    id: output_cold
    pin: P7
  - platform: ledc
    id: output_warm
    pin: P6

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    restore_mode: RESTORE_DEFAULT_OFF
``` 

Here are some pics for reference:
![20231030_104021](https://github.com/tuya-cloudcutter/tuya-cloudcutter/assets/139799765/c5ddf291-3f5d-4069-828d-772daf8d53a7)
![20231030_104140](https://github.com/tuya-cloudcutter/tuya-cloudcutter/assets/139799765/3f4b7fbc-1de4-4a02-af1b-66553e1b1034)
