### ISSUE TITLE
restore_mode not working

### ISSUE THREAD

**Issue by nedyarrd** [libretiny-eu/libretiny#198]
It looks like restore mode, or anything else what needs to be writen to persistent memory is not working. I have LSC bulbs flashed with LibreTiny ESPHome. When I try to set restore_mode it makes only "on" and "off" like stated, but don't remember last state and state of color temperature.

**Comment by Cossid** [comment]
`restore_mode` works fine on every device I have.  "on" and "off" are not valid settings, see https://esphome.io/components/light/index.html?highlight=restore_mode.  Additionally, settings are not saved instantly, by default, they are only updated every 60 seconds to avoid flash wearing.  Additionally if you use anything like groups, they may be overriding the restored settings when they sync.

**Comment by zoidy** [comment]
> Edit: there are also quirks as to when save triggers when the mode changes, but the on/off state does not. You may want to consider calling the preferences save when you set the state you desire.

Like in the original post, `restore_mode` doesn't work for me (I have `CMA19-60W-AL-9ACK ` lights). Could you elaborate on how to do preferences save?

**Comment by Cossid** [comment]
There was a [bug found](https://github.com/esphome/esphome/pull/7642) and patched in 2024.10.1 that sometimes led to preferences not being saved, so start by updating to that version or newer.

Additionally, you can add a button to manually save preferences on demand;
```yaml
button:
  - platform: template
    id: save_preferences
    name: "Save Preferences"
    entity_category: diagnostic
    on_press:
      - lambda: global_preferences->sync();
```
