### ISSUE TITLE
How to use forked `libretiny` inside ESPHome?

### ISSUE THREAD

**Issue by lmcd** [libretiny-eu/libretiny#201]
What's the easiest way to tinker with the `libretiny` codebase inside `ESPHome`?

**Comment by Cossid** [comment]
I believe it is something like

```yaml
bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: 0.0.0
    source: https://github.com/lmcd/libretiny.git
```
add `#branch-name` if you have a custom branch.
