### ISSUE TITLE
arm-none-eabi-g++: not found

### ISSUE THREAD

**Issue by hunhejj** [libretiny-eu/libretiny#238]
I am getting the error `arm-none-eabi-g++: not found` when building a libretiny firmware.

ESPHome: v2023.12.15 (Docker)
Host: Raspberry Pi 4 (4 GB)

Sample device:
```
esphome:
  name: libretiny_test

bk72xx:
  board: generic-bk7231n-qfn32-tuya

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Logs:
[logs_libretiny-test_compile.txt](https://github.com/libretiny-eu/libretiny/files/13863367/logs_libretiny-test_compile.txt)
