### ISSUE TITLE
output.libretiny_pwm not working

### ISSUE THREAD

**Issue by cremer42** [libretiny-eu/libretiny#250]
Hi all, I am new to libretiny, and this one has been throwing me through a loop... I have been getting an error saying platform not found: 'output.libretiny_pwm' 

I am attempting to finalize cloudcutting of some tuya downlights and this is the only thing stopping me. I was able to get the code to be accepted when using "output.ledc" but clearly that doesnt work with the lights anymore.  Below is my esp yaml.

attached is an image of the errors.

```
esphome:
  name: office-downlight-01
  friendly_name: office-downlight-01

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

ota:
  password: !secret ota_pass001

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P8
  - platform: libretiny_pwm
    id: output_green
    pin: P24
  - platform: libretiny_pwm
    id: output_blue
    pin: P26
  - platform: libretiny_pwm
    id: output_cold
    pin: P7
  - platform: libretiny_pwm
    id: output_warm
    pin: P6

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
```
![libretiny](https://github.com/libretiny-eu/libretiny/assets/128273443/4225c019-2479-4dae-8fa2-83f1b08931f6)
