### ISSUE TITLE
restore_mode ALWAYS_OFF not working on generic-bk7231n-qfn32-tuya

### ISSUE THREAD

**Issue by marcohald** [libretiny-eu/libretiny#261]
When restore_mode is set to ALWAYS_OFF it does restore the last config.
However I'm not sure if this is a ESPHome Problem or Homeassitent pushes back the last Config
Using Version ESPHome 2024.2.1 and  libretiny @ 1.4.1
This is the relevant part of  my yml:
```
sm2235:
  clock_pin: P26
  data_pin: P24
  max_power_color_channels: "11"
  max_power_white_channels: "11"

output:
  - platform: sm2235
    id: output_red
    channel: "2"
    zero_means_zero: True
    min_power: 0.003
  - platform: sm2235
    id: output_green
    channel: "1"
    zero_means_zero: True
    min_power: 0.003
  - platform: sm2235
    id: output_blue
    channel: "0"
    zero_means_zero: True
    min_power: 0.003
  - platform: sm2235
    id: output_cold
    channel: "4"
    zero_means_zero: True
    min_power: 0.013
  - platform: sm2235
    id: output_warm
    channel: "3"
    zero_means_zero: True
    min_power: 0.015

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    restore_mode: ALWAYS_OFF

```
