### ISSUE TITLE
bk7231n ADC on PIN9 not available in ESPHome 2024.11.2

### ISSUE THREAD

**Issue by majuss** [libretiny-eu/libretiny#301]
```
esphome:
  name: trafficlight1
  friendly_name: trafficlight1

bk72xx:
  board: generic-bk7231n-qfn32-tuya

wifi:

logger:

api:

ota:
  platform: esphome

web_server:

captive_portal:

output:
  - platform: libretiny_pwm
    id: red
    frequency: 1000 Hz
    pin: PWM5
  - platform: libretiny_pwm
    id: blue
    frequency: 1000 Hz
    pin: PWM0
  - platform: libretiny_pwm
    id: green
    frequency: 1000 Hz
    pin: PWM4
  - platform: libretiny_pwm
    id: cw
    frequency: 1000 Hz
    pin: PWM2
  - platform: libretiny_pwm
    id: ww
    frequency: 1000 Hz
    pin: PWM1

light:
  - platform: rgb
    name: "Living Room Lights"
    red: red
    green: green
    blue: blue

  - platform: cwww
    name: whitelight
    cold_white: cw
    warm_white: ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

binary_sensor:
  - platform: gpio
    pin: P14
    name: "PIR Sensor"
    device_class: motion
  - platform: gpio
    pin:
      number: P20
      inverted: true
    name: "Button"

sensor:
  - platform: adc
    name: sensor
    pin: P9
    filters:
      - multiply: 3.3
```
I try to use P9 on an ADC, my device has a photoresistor connected to it. The datasheet mentions that P9 is reserved for "VBAT" which also indicates an ADC pin. But still the board definition available in ESPHome thinks that P9 is not a valid ADC pin.
